version: 0.1 

environment_variables: 
   plaintext: 
     DJANGO_SETTINGS_MODULE: config.settings.test 
     SECRET_KEY: nosecret 
     DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3 
     DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3 
     OPBEAT_ENABLED: False 
phases: 
  pre_build: 
    commands: 
      - echo Prebuild ops 
      - pip3 install -r requirement.txt 
      - pip3 install sqlparse
      - pip3 install config
      
     
  build: 
    commands: 
      - echo Building the application 
      - python manage.py runserver 0.0.0.0:8001
  post_build: 
    commands: 
      - echo Build completed on `date`
